[package]
name = "mini-ingestion"
version = "0.1.0"
edition = "2024"

[dependencies]
rdkafka = { version = "0.37", features = ["cmake-build"] }
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
serde_json = "1"
serde = "1"
clickhouse = { version = "0.13.2", features = ["inserter"] }

